name: Variable Workflow

on:
  push:
    branches:
      - main

env:
    GLOBAL_VAR: "This is global variable"
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      JOB_VAR: "This is a Job variable"

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Print global variable
        run: echo "Global variable $GLOBAL_VAR"

      - name: Set up local job-level variable
        run: echo "Global variable $JOB_VAR"

      - name: Print job-level variable
        run: echo "Job-level variable $JOB_VAR"

      - name: Set up local step-level variable
        env:
          STEP_VAR: "This is a step-level variable"
        run: echo "Step-level variable $STEP_VAR"
